-- 1. Insert ENSEIGNANT (Teachers)
-- Required: NO_ENSEIGNANT, TYPE, SEXE, NOM, PRENOM, ADRESSE, CP, VILLE, PAYS
INSERT INTO ENSEIGNANT (NO_ENSEIGNANT, TYPE, SEXE, NOM, PRENOM, ADRESSE, CP, VILLE, PAYS, ENC_UBO_EMAIL, TEL_PORT)
VALUES (1, 'PROF', 'H', 'LALLALI', 'Mourad', '6 Avenue Le Gorgeu', '29200', 'BREST', 'FRANCE', 'mourad.lallali@univ-brest.fr', '0600000001');

INSERT INTO ENSEIGNANT (NO_ENSEIGNANT, TYPE, SEXE, NOM, PRENOM, ADRESSE, CP, VILLE, PAYS, ENC_UBO_EMAIL, TEL_PORT)
VALUES (2, 'MCF', 'F', 'POULET', 'Sophie', '6 Avenue Le Gorgeu', '29200', 'BREST', 'FRANCE', 'sophie.poulet@univ-brest.fr', '0600000002');


-- 2. Insert FORMATION (Degree)
-- Required: CODE_FORMATION, DIPLOME, N0_ANNEE, NOM_FORMATION, DOUBLE_DIPLOME
INSERT INTO FORMATION (CODE_FORMATION, DIPLOME, N0_ANNEE, NOM_FORMATION, DOUBLE_DIPLOME, DEBUT_HABILITATION, FIN_HABILITATION)
VALUES ('M2DOSI', 'M', 2, 'Master 2 DOSI', 'N', TO_DATE('2022-09-01', 'YYYY-MM-DD'), TO_DATE('2026-09-01', 'YYYY-MM-DD'));


-- 3. Insert PROMOTION (Class Year)
-- Required: ANNEE_PRO, SIGLE_PRO, NB_ETU_SOUHAITE, ETAT_PRESELECTION
INSERT INTO PROMOTION (ANNEE_PRO, CODE_FORMATION, NO_ENSEIGNANT, SIGLE_PRO, NB_ETU_SOUHAITE, ETAT_PRESELECTION, DATE_RENTREE, LIEU_RENTREE)
VALUES ('2025-2026', 'M2DOSI', 1, 'DOSI25', 24, 'TER', TO_DATE('2025-09-04', 'YYYY-MM-DD'), 'Salle C205');


-- 4. Insert ETUDIANT (Students)
-- WARNING: Your table has MANY required fields. This looks scary but is necessary.
INSERT INTO ETUDIANT (
    NO_ETUDIANT_NAT, ANNEE_PRO, CODE_COM, NO_ETUDIANT_UBO, SEXE, NOM, PRENOM,
    DATE_NAISSANCE, LIEU_NAISSANCE, SITUATION, NATIONALITE,
    PERM_ADRESSE, PERM_CP, PERM_VILLE, PERM_PAYS,
    DERNIER_DIPLOME, UNIVERSITE, SIGLE_ETU, COMPTE_CRI, UBO_EMAIL, EST_DIPLOME
) VALUES (
             'E2025001', '2025-2026', NULL, '2025001', 'H', 'BEN SALAH', 'Ahmed',
             TO_DATE('1999-05-15', 'YYYY-MM-DD'), 'Casablanca', 'CEL', 'Marocaine',
             '12 Rue de Siam', '29200', 'Brest', 'France',
             'Master 1 Info', 'UBO', 'ABS', 'benahm01', 'ahmed.bensalah@univ-brest.fr', 'N'
         );

INSERT INTO ETUDIANT (
    NO_ETUDIANT_NAT, ANNEE_PRO, CODE_COM, NO_ETUDIANT_UBO, SEXE, NOM, PRENOM,
    DATE_NAISSANCE, LIEU_NAISSANCE, SITUATION, NATIONALITE,
    PERM_ADRESSE, PERM_CP, PERM_VILLE, PERM_PAYS,
    DERNIER_DIPLOME, UNIVERSITE, SIGLE_ETU, COMPTE_CRI, UBO_EMAIL, EST_DIPLOME
) VALUES (
             'E2025002', '2025-2026', NULL, '2025002', 'F', 'DUPONT', 'Marie',
             TO_DATE('2000-03-20', 'YYYY-MM-DD'), 'Rennes', 'CEL', 'Française',
             '5 Rue Jaurès', '29200', 'Brest', 'France',
             'Master 1 TIL', 'UBS', 'MDU', 'dupont02', 'marie.dupont@univ-brest.fr', 'N'
         );